"""Add gamestate

Revision ID: 2e3c69481c89
Revises: be31b1dc5641
Create Date: 2023-05-04 12:34:46.791735

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2e3c69481c89'
down_revision = 'be31b1dc5641'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamestate',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('world_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_states', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rng', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gamestate')
    # ### end Alembic commands ###
