"""Add game commands

Revision ID: 5c59504f90b2
Revises: a5624f2db2f1
Create Date: 2023-05-19 16:29:57.538628

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5c59504f90b2'
down_revision = 'a5624f2db2f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamecommand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.Column('command', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamecommand_session_id'), 'gamecommand', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gamecommand_session_id'), table_name='gamecommand')
    op.drop_table('gamecommand')
    # ### end Alembic commands ###
