"""Minor schema changes

Revision ID: a5624f2db2f1
Revises: 2e3c69481c89
Create Date: 2023-05-11 14:08:25.377566

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a5624f2db2f1'
down_revision = '2e3c69481c89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gptdialogue', 'character_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gptdialogue', 'character_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
