"""first

Revision ID: be31b1dc5641
Revises: 
Create Date: 2023-04-29 19:05:42.313599

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'be31b1dc5641'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aiimage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aiimage_model_version'), 'aiimage', ['model_version'], unique=False)
    op.create_table('gptdialogue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stop_words', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gptdialogue_character_name'), 'gptdialogue', ['character_name'], unique=False)
    op.create_index(op.f('ix_gptdialogue_context'), 'gptdialogue', ['context'], unique=False)
    op.create_index(op.f('ix_gptdialogue_model_version'), 'gptdialogue', ['model_version'], unique=False)
    op.create_index(op.f('ix_gptdialogue_question'), 'gptdialogue', ['question'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gptdialogue_question'), table_name='gptdialogue')
    op.drop_index(op.f('ix_gptdialogue_model_version'), table_name='gptdialogue')
    op.drop_index(op.f('ix_gptdialogue_context'), table_name='gptdialogue')
    op.drop_index(op.f('ix_gptdialogue_character_name'), table_name='gptdialogue')
    op.drop_table('gptdialogue')
    op.drop_index(op.f('ix_aiimage_model_version'), table_name='aiimage')
    op.drop_table('aiimage')
    # ### end Alembic commands ###
