service: gptif-magnum
frameworkVersion: '3'

provider:
  name: aws
  memorySize: 512
  timeout: 30
  ecr:
    images:
      gptif_image:
        path: ..
        file: aws_server.dockerfile
  region: us-east-1
  stage: ${opt:stage, "dev"}
  environment:
    LOG_LEVEL: ${opt:loglevel, 'DEBUG'}

functions:
  api:
    image:
      name: gptif_image
    environment:
      STAGE: ${self:provider.stage}
      POWERTOOLS_SERVICE_NAME: GptIfBackend
      POWERTOOLS_METRICS_NAMESPACE: GptIf
      SPACY_DATA_DIR: /var/task
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /api/{proxy+}
          method: any
          cors: true
      - http:
          path: /api
          method: any
          cors: true
